M48
; DRILL file {KiCad 8.0.4} date 2024-12-11T23:07:34+0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-11T23:07:34+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.2831Y-2.5085
X5.5107Y-2.5085
T2
X4.449Y-3.341
X4.849Y-5.444
X5.781Y-5.454
X6.3509Y-3.352
M30
